"""aggiornato price_per_hour per sfruttare Decimal per maggiore precisione per calcoli finanziari

Revision ID: 049c22a4fecd
Revises: 7297d2927d6f
Create Date: 2025-03-23 10:48:49.035474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '049c22a4fecd'
down_revision: Union[str, None] = '7297d2927d6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_boats_statuses_description', table_name='boat_statuses')
    op.drop_index('ix_boats_statuses_id', table_name='boat_statuses')
    op.drop_index('ix_boats_statuses_name', table_name='boat_statuses')
    op.create_index(op.f('ix_boat_statuses_description'), 'boat_statuses', ['description'], unique=False)
    op.create_index(op.f('ix_boat_statuses_id'), 'boat_statuses', ['id'], unique=False)
    op.create_index(op.f('ix_boat_statuses_name'), 'boat_statuses', ['name'], unique=True)
    op.alter_column('boats', 'price_per_hour',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boats', 'price_per_hour',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_boat_statuses_name'), table_name='boat_statuses')
    op.drop_index(op.f('ix_boat_statuses_id'), table_name='boat_statuses')
    op.drop_index(op.f('ix_boat_statuses_description'), table_name='boat_statuses')
    op.create_index('ix_boats_statuses_name', 'boat_statuses', ['name'], unique=True)
    op.create_index('ix_boats_statuses_id', 'boat_statuses', ['id'], unique=False)
    op.create_index('ix_boats_statuses_description', 'boat_statuses', ['description'], unique=False)
    # ### end Alembic commands ###
