"""aggiornamento name di boat statuses come enum per garantre maggiore controllo

Revision ID: 0d5854077637
Revises: e2b8e2fc0510
Create Date: 2025-03-23 21:06:02.791208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0d5854077637'
down_revision: Union[str, None] = 'e2b8e2fc0510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boat_statuses', 'name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('AVAILABLE', 'MAINTENANCE', 'OUT_OF_SERVICE', name='boatstatusesvalues', create_constraint=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boat_statuses', 'name',
               existing_type=sa.Enum('AVAILABLE', 'MAINTENANCE', 'OUT_OF_SERVICE', name='boatstatusesvalues', create_constraint=True),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
