"""migrations init

Revision ID: 7297d2927d6f
Revises: 
Create Date: 2025-03-22 22:43:43.210738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7297d2927d6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boat_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boats_statuses_description'), 'boat_statuses', ['description'], unique=False)
    op.create_index(op.f('ix_boats_statuses_id'), 'boat_statuses', ['id'], unique=False)
    op.create_index(op.f('ix_boats_statuses_name'), 'boat_statuses', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='2025-03-22 21:43:42.744317', nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default='2025-03-22 21:43:42.744359', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('boats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('seat', sa.Integer(), nullable=False),
    sa.Column('price_per_hour', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('boat_status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='2025-03-22 21:43:42.745582', nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default='2025-03-22 21:43:42.745614', nullable=False),
    sa.ForeignKeyConstraint(['boat_status_id'], ['boat_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boats_boat_status_id'), 'boats', ['boat_status_id'], unique=False)
    op.create_index(op.f('ix_boats_description'), 'boats', ['description'], unique=False)
    op.create_index(op.f('ix_boats_id'), 'boats', ['id'], unique=False)
    op.create_index(op.f('ix_boats_location'), 'boats', ['location'], unique=False)
    op.create_index(op.f('ix_boats_name'), 'boats', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='2025-03-22 21:43:42.742087', nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default='2025-03-22 21:43:42.742165', nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_firstname'), 'users', ['firstname'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_lastname'), 'users', ['lastname'], unique=False)
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_index(op.f('ix_users_lastname'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_firstname'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_boats_name'), table_name='boats')
    op.drop_index(op.f('ix_boats_location'), table_name='boats')
    op.drop_index(op.f('ix_boats_id'), table_name='boats')
    op.drop_index(op.f('ix_boats_description'), table_name='boats')
    op.drop_index(op.f('ix_boats_boat_status_id'), table_name='boats')
    op.drop_table('boats')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_boats_statuses_name'), table_name='boat_statuses')
    op.drop_index(op.f('ix_boats_statuses_id'), table_name='boat_statuses')
    op.drop_index(op.f('ix_boats_statuses_description'), table_name='boat_statuses')
    op.drop_table('boat_statuses')
    # ### end Alembic commands ###
