"""implementata tabella bookings

Revision ID: e2b8e2fc0510
Revises: 049c22a4fecd
Create Date: 2025-03-23 12:38:00.741065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2b8e2fc0510'
down_revision: Union[str, None] = '049c22a4fecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seat', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('boat_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('reservation_code', sa.String(length=255), nullable=False),
    sa.Column('payment_method', sa.Enum('BANK_TRANSFER', 'CASH', 'CREDIT_CARD', name='paymentmethods', create_constraint=True), nullable=False),
    sa.Column('reservation_status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='bookingstatuses', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='2025-03-23 11:38:00.512985', nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default='2025-03-23 11:38:00.513013', nullable=False),
    sa.ForeignKeyConstraint(['boat_id'], ['boats.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_reservation_status'), 'bookings', ['reservation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_reservation_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
