"""fix role con enum

Revision ID: f149d0a9e951
Revises: 6edf7d4d63c2
Create Date: 2025-03-31 00:22:10.468706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f149d0a9e951'
down_revision: Union[str, None] = '6edf7d4d63c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('ADMIN', 'CUSTOMER', 'PUBLIC', name='roles', create_constraint=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=sa.Enum('ADMIN', 'CUSTOMER', 'PUBLIC', name='roles', create_constraint=True),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
